export default [
  {
    id: 1,
    band: 'Iron Maiden',
    date: '19/01/2002',
    place: 'Maracanã Stadium',
    city: 'Rio de Janeiro',
    country: 'Brazil',
    picture: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Iron_Maiden_in_the_Palais_Omnisports_of_Paris-Bercy_%28France%29.jpg',
  },
  {
    id: 2,
    band: 'Iron Maiden',
    date: '18/07/1999',
    place: 'Orpheum Theatre',
    city: 'Boston',
    country: 'USA',
    picture: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Iron_Maiden_in_the_Palais_Omnisports_of_Paris-Bercy_%28France%29.jpg',
  },
  {
    id: 3,
    band: 'Iron Maiden',
    date: '22/08/1992',
    place: 'Donington Park',
    city: 'Donington',
    country: 'England',
    picture: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Iron_Maiden_in_the_Palais_Omnisports_of_Paris-Bercy_%28France%29.jpg',
  },
  {
    id: 4,
    band: 'Iron Maiden',
    date: '14/03/1985',
    place: 'Long Beach Arena',
    city: 'Californie',
    country: 'USA',
    picture: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Iron_Maiden_in_the_Palais_Omnisports_of_Paris-Bercy_%28France%29.jpg',
  },
];
